package com.shellbridge.app.ui.theme

import androidx.compose.ui.graphics.Color

data class TerminalPalette(
    val name: String,
    val background: Color,
    val foreground: Color,
    val cursor: Color,
    val selection: Color,
    val black: Color,
    val red: Color,
    val green: Color,
    val yellow: Color,
    val blue: Color,
    val magenta: Color,
    val cyan: Color,
    val white: Color,
    val brightBlack: Color,
    val brightRed: Color,
    val brightGreen: Color,
    val brightYellow: Color,
    val brightBlue: Color,
    val brightMagenta: Color,
    val brightCyan: Color,
    val brightWhite: Color,
    val surface: Color,
    val surfaceVariant: Color,
    val onSurface: Color,
    val accent: Color
)

object TerminalThemes {
    val catppuccinMocha = TerminalPalette(
        name = "Catppuccin Mocha",
        background = Color(0xFF1E1E2E),
        foreground = Color(0xFFCDD6F4),
        cursor = Color(0xFFF5E0DC),
        selection = Color(0xFF45475A),
        black = Color(0xFF45475A),
        red = Color(0xFFF38BA8),
        green = Color(0xFFA6E3A1),
        yellow = Color(0xFFF9E2AF),
        blue = Color(0xFF89B4FA),
        magenta = Color(0xFFF5C2E7),
        cyan = Color(0xFF94E2D5),
        white = Color(0xFFBAC2DE),
        brightBlack = Color(0xFF585B70),
        brightRed = Color(0xFFF38BA8),
        brightGreen = Color(0xFFA6E3A1),
        brightYellow = Color(0xFFF9E2AF),
        brightBlue = Color(0xFF89B4FA),
        brightMagenta = Color(0xFFF5C2E7),
        brightCyan = Color(0xFF94E2D5),
        brightWhite = Color(0xFFA6ADC8),
        surface = Color(0xFF313244),
        surfaceVariant = Color(0xFF45475A),
        onSurface = Color(0xFFCDD6F4),
        accent = Color(0xFF89B4FA)
    )

    val tokyoNight = TerminalPalette(
        name = "Tokyo Night",
        background = Color(0xFF1A1B26),
        foreground = Color(0xFFC0CAF5),
        cursor = Color(0xFFC0CAF5),
        selection = Color(0xFF33467C),
        black = Color(0xFF15161E),
        red = Color(0xFFF7768E),
        green = Color(0xFF9ECE6A),
        yellow = Color(0xFFE0AF68),
        blue = Color(0xFF7AA2F7),
        magenta = Color(0xFFBB9AF7),
        cyan = Color(0xFF7DCFFF),
        white = Color(0xFFA9B1D6),
        brightBlack = Color(0xFF414868),
        brightRed = Color(0xFFF7768E),
        brightGreen = Color(0xFF9ECE6A),
        brightYellow = Color(0xFFE0AF68),
        brightBlue = Color(0xFF7AA2F7),
        brightMagenta = Color(0xFFBB9AF7),
        brightCyan = Color(0xFF7DCFFF),
        brightWhite = Color(0xFFC0CAF5),
        surface = Color(0xFF24283B),
        surfaceVariant = Color(0xFF414868),
        onSurface = Color(0xFFC0CAF5),
        accent = Color(0xFF7AA2F7)
    )

    val dracula = TerminalPalette(
        name = "Dracula",
        background = Color(0xFF282A36),
        foreground = Color(0xFFF8F8F2),
        cursor = Color(0xFFF8F8F2),
        selection = Color(0xFF44475A),
        black = Color(0xFF21222C),
        red = Color(0xFFFF5555),
        green = Color(0xFF50FA7B),
        yellow = Color(0xFFF1FA8C),
        blue = Color(0xFFBD93F9),
        magenta = Color(0xFFFF79C6),
        cyan = Color(0xFF8BE9FD),
        white = Color(0xFFF8F8F2),
        brightBlack = Color(0xFF6272A4),
        brightRed = Color(0xFFFF6E6E),
        brightGreen = Color(0xFF69FF94),
        brightYellow = Color(0xFFFFFFA5),
        brightBlue = Color(0xFFD6ACFF),
        brightMagenta = Color(0xFFFF92DF),
        brightCyan = Color(0xFFA4FFFF),
        brightWhite = Color(0xFFFFFFFF),
        surface = Color(0xFF343746),
        surfaceVariant = Color(0xFF44475A),
        onSurface = Color(0xFFF8F8F2),
        accent = Color(0xFFBD93F9)
    )

    val nord = TerminalPalette(
        name = "Nord",
        background = Color(0xFF2E3440),
        foreground = Color(0xFFD8DEE9),
        cursor = Color(0xFFD8DEE9),
        selection = Color(0xFF434C5E),
        black = Color(0xFF3B4252),
        red = Color(0xFFBF616A),
        green = Color(0xFFA3BE8C),
        yellow = Color(0xFFEBCB8B),
        blue = Color(0xFF81A1C1),
        magenta = Color(0xFFB48EAD),
        cyan = Color(0xFF88C0D0),
        white = Color(0xFFE5E9F0),
        brightBlack = Color(0xFF4C566A),
        brightRed = Color(0xFFBF616A),
        brightGreen = Color(0xFFA3BE8C),
        brightYellow = Color(0xFFEBCB8B),
        brightBlue = Color(0xFF81A1C1),
        brightMagenta = Color(0xFFB48EAD),
        brightCyan = Color(0xFF88C0D0),
        brightWhite = Color(0xFFECEFF4),
        surface = Color(0xFF3B4252),
        surfaceVariant = Color(0xFF434C5E),
        onSurface = Color(0xFFD8DEE9),
        accent = Color(0xFF88C0D0)
    )

    val gruvbox = TerminalPalette(
        name = "Gruvbox",
        background = Color(0xFF282828),
        foreground = Color(0xFFEBDBB2),
        cursor = Color(0xFFEBDBB2),
        selection = Color(0xFF504945),
        black = Color(0xFF282828),
        red = Color(0xFFCC241D),
        green = Color(0xFF98971A),
        yellow = Color(0xFFD79921),
        blue = Color(0xFF458588),
        magenta = Color(0xFFB16286),
        cyan = Color(0xFF689D6A),
        white = Color(0xFFA89984),
        brightBlack = Color(0xFF928374),
        brightRed = Color(0xFFFB4934),
        brightGreen = Color(0xFFB8BB26),
        brightYellow = Color(0xFFFABD2F),
        brightBlue = Color(0xFF83A598),
        brightMagenta = Color(0xFFD3869B),
        brightCyan = Color(0xFF8EC07C),
        brightWhite = Color(0xFFEBDBB2),
        surface = Color(0xFF3C3836),
        surfaceVariant = Color(0xFF504945),
        onSurface = Color(0xFFEBDBB2),
        accent = Color(0xFFD79921)
    )

    val monokai = TerminalPalette(
        name = "Monokai",
        background = Color(0xFF272822),
        foreground = Color(0xFFF8F8F2),
        cursor = Color(0xFFF8F8F0),
        selection = Color(0xFF49483E),
        black = Color(0xFF272822),
        red = Color(0xFFF92672),
        green = Color(0xFFA6E22E),
        yellow = Color(0xFFF4BF75),
        blue = Color(0xFF66D9EF),
        magenta = Color(0xFFAE81FF),
        cyan = Color(0xFFA1EFE4),
        white = Color(0xFFF8F8F2),
        brightBlack = Color(0xFF75715E),
        brightRed = Color(0xFFF92672),
        brightGreen = Color(0xFFA6E22E),
        brightYellow = Color(0xFFF4BF75),
        brightBlue = Color(0xFF66D9EF),
        brightMagenta = Color(0xFFAE81FF),
        brightCyan = Color(0xFFA1EFE4),
        brightWhite = Color(0xFFF9F8F5),
        surface = Color(0xFF3E3D32),
        surfaceVariant = Color(0xFF49483E),
        onSurface = Color(0xFFF8F8F2),
        accent = Color(0xFFA6E22E)
    )

    val oneDark = TerminalPalette(
        name = "One Dark",
        background = Color(0xFF282C34),
        foreground = Color(0xFFABB2BF),
        cursor = Color(0xFF528BFF),
        selection = Color(0xFF3E4451),
        black = Color(0xFF282C34),
        red = Color(0xFFE06C75),
        green = Color(0xFF98C379),
        yellow = Color(0xFFE5C07B),
        blue = Color(0xFF61AFEF),
        magenta = Color(0xFFC678DD),
        cyan = Color(0xFF56B6C2),
        white = Color(0xFFABB2BF),
        brightBlack = Color(0xFF5C6370),
        brightRed = Color(0xFFE06C75),
        brightGreen = Color(0xFF98C379),
        brightYellow = Color(0xFFE5C07B),
        brightBlue = Color(0xFF61AFEF),
        brightMagenta = Color(0xFFC678DD),
        brightCyan = Color(0xFF56B6C2),
        brightWhite = Color(0xFFFFFFFF),
        surface = Color(0xFF2C313C),
        surfaceVariant = Color(0xFF3E4451),
        onSurface = Color(0xFFABB2BF),
        accent = Color(0xFF61AFEF)
    )

    val rosePine = TerminalPalette(
        name = "Rosé Pine",
        background = Color(0xFF191724),
        foreground = Color(0xFFE0DEF4),
        cursor = Color(0xFFE0DEF4),
        selection = Color(0xFF2A283E),
        black = Color(0xFF26233A),
        red = Color(0xFFEB6F92),
        green = Color(0xFF31748F),
        yellow = Color(0xFFF6C177),
        blue = Color(0xFF9CCFD8),
        magenta = Color(0xFFC4A7E7),
        cyan = Color(0xFFEBBCBA),
        white = Color(0xFFE0DEF4),
        brightBlack = Color(0xFF6E6A86),
        brightRed = Color(0xFFEB6F92),
        brightGreen = Color(0xFF31748F),
        brightYellow = Color(0xFFF6C177),
        brightBlue = Color(0xFF9CCFD8),
        brightMagenta = Color(0xFFC4A7E7),
        brightCyan = Color(0xFFEBBCBA),
        brightWhite = Color(0xFFF6F1FF),
        surface = Color(0xFF1F1D2E),
        surfaceVariant = Color(0xFF2A283E),
        onSurface = Color(0xFFE0DEF4),
        accent = Color(0xFF9CCFD8)
    )

    val allPalettes = listOf(
        catppuccinMocha, tokyoNight, dracula, nord,
        gruvbox, monokai, oneDark, rosePine
    )
}
